AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for setting up a Cognito Userpool
Parameters:
  UserEmail:
    Type: String
    Default: vbhamidi@amazon.com
    Description: Email address to add to the pool
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UsernameAttributes:
        - email
      UserPoolName: gt-userpool
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  CognitoUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: User
      GroupName: user
      Precedence: 1
      UserPoolId: !Ref CognitoUserPool

  UserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref UserEmail
      Username: !Ref UserEmail
      UserPoolId: !Ref CognitoUserPool

  UserGroupAttachment:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    Properties:
      GroupName: !Ref CognitoUserGroup
      Username: !Ref UserEmail
      UserPoolId: !Ref CognitoUserPool
  CognitoClientId:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - CognitoUserPool
    Properties:
      ClientName: gt-userpool-clientname
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      GenerateSecret: true
      UserPoolId: !Ref CognitoUserPool
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Join
        - ''
        - - 'predictive-maintenance'
          - !Ref 'AWS::AccountId'
      UserPoolId: !Ref CognitoUserPool
Outputs:
  CognitoUserPool:
    Description: CognitoUser pool
    Value: !Ref CognitoUserPool
    Export:
      Name: CognitoUserPool
  CognitoUserGroup:
    Description: CognitoUser pool
    Value: !Ref CognitoUserGroup
    Export:
      Name: CognitoUserGroup
  CognitoClientId:
    Description: CognitoUser pool client ID
    Value: !Ref CognitoClientId
    Export:
      Name: CognitoClientId