AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation to deploy Lambdas and Firehose delivery stream required
  for running GroundTruth Pipeline
Parameters:
  S3OutputBucket:
    Type: String
    Description: S3 output bucket for storing the Amazon SageMaker model and training data.
  CustomerId:
    Description: The customer id value to be used while collecting your product preferences
      via GroundTruth labelling
    Type: String
    MinLength: 1
    MaxLength: 16
    Default: 11464196
    AllowedPattern: "[0-9]+"
Mappings:
  Function:
    PredictiveMaintenance:
      S3Bucket: "workshop-assets"
      S3Key: predictive-maintenance-using-machine-learning/v1.0.0/functions/
  Notebook:
    PredictiveMaintenance:
      S3Bucket: "workshop-assets"
      S3Key: /predictive-maintenance-using-machine-learning/v1.0.0/notebooks/
Resources:
  GTWorkTeam:
    Type: AWS::SageMaker::Workteam
    Properties:
      Description: Workteam for the labeling job
      MemberDefinitions:
        - CognitoMemberDefinition:
            CognitoClientId: !ImportValue CognitoClientId
            CognitoUserGroup: !ImportValue CognitoUserGroup
            CognitoUserPool: !ImportValue CognitoUserPool
      WorkteamName: Predictive-maintenance-rca-team