AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation initializes the account with resouces used by other stacks
Parameters:
  WorkshopName:
    Type: String
    Default: pred-maint
    Description: Name of the workshop.
Resources:
  S3OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Ref WorkshopName
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  GTCustomJobExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt 'PostLabelLambdaSMGTExecutionRole.Arn'
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: GTCustomJobExecutionRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      Path: /service-role/
  PostLabelLambdaSMGTExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: PostLabelLambdaSMGTExecutionRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /
  PreLabelingLambdaSMGTExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: PreLabelingLambdaSMGTExecutionRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /
  FirehoseDeliveryIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
  FirehoseDeliveryIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EventStreamFirehoseIAMPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'S3OutputBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'S3OutputBucket'
                  - /*
      Roles:
        - !Ref 'FirehoseDeliveryIAMRole'
        - !Ref 'GTCustomJobExecutionRole'
Outputs:
  S3OutputBucket:
    Description: S3 output bucket
    Value: !Ref S3OutputBucket
    Export:
      Name: S3OutputBucket
  GTCustomJobExecutionRoleARN:
    Description: GTCustomJobExecutionRoleARN
    Value: !GetAtt 'GTCustomJobExecutionRole.Arn'
    Export:
      Name: GTCustomJobExecutionRoleARN
  PreLabelingLambdaSMGTExecutionRoleARN:
    Description: PreLabelingLambdaSMGTExecutionRoleARN
    Value: !GetAtt 'PreLabelingLambdaSMGTExecutionRole.Arn'
    Export:
      Name: PreLabelingLambdaSMGTExecutionRoleARN
  PostLabelLambdaSMGTExecutionRoleARN:
    Description: PostLabelLambdaSMGTExecutionRoleARN
    Value: !GetAtt 'PostLabelLambdaSMGTExecutionRole.Arn'
    Export:
      Name: PostLabelLambdaSMGTExecutionRoleARN
  FirehoseDeliveryIAMRoleARN:
    Description: FirehoseDeliveryIAMRoleARN
    Value: !GetAtt 'FirehoseDeliveryIAMRole.Arn'
    Export:
      Name: FirehoseDeliveryIAMRoleARN