Description: >
  This template will deploy a Sagemaker notebook instance with the required notebooks installed

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Recycle-arm

  S3Bucket:
      Description: S3 bucket where the Cloudformation/Scripts/config files are placed
      Type: String
      Default: reinvent2018-builder-fair-recycle-arm

  NotebookInstanceType:
        Description: Notebook instance type
        Type: String
        Default: ml.m4.2xlarge


Resources:

  SagemakerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess'
        - "arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess"
        - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"

  SagemakerLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub ${EnvironmentName}LifecycleConfig
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              cd /home/ec2-user/SageMaker
              aws s3 cp s3://${S3Bucket}-${AWS::Region}/sagemaker-notebooks/ . --recursive

              sed -i.bak 's/#s3_data_bucket/${S3Bucket}-${AWS::Region}/g' *.ipynb
              sed -i.bak 's/#region/${AWS::Region}/g' *.ipynb

              sed -i.bak 's/#iam_role/arn:aws:iam::${AWS::AccountId}:role\/${SagemakerRole}/g' *.ipynb

              rm *.bak

              chown ec2-user:ec2-user *

  SagemakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    DependsOn:
      - SagemakerLifecycleConfig
    Properties:
      DirectInternetAccess: Enabled
      NotebookInstanceName: !Sub ${EnvironmentName}-Notebook
      InstanceType: !Ref NotebookInstanceType
      LifecycleConfigName: !GetAtt SagemakerLifecycleConfig.NotebookInstanceLifecycleConfigName
      RoleArn: !GetAtt SagemakerRole.Arn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Sagemaker Notebook


Outputs:


  SagemakerRoleArn:
    Description: IAM role name
    Value: !GetAtt SagemakerRole.Arn

  SagemakerNotebookInstanceName:
    Description: Name of the sagemaker notebook
    Value: !GetAtt SagemakerNotebookInstance.NotebookInstanceName
